import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

const menus = [
  { name: "Dashboard", path: "/dashboard" },
  { name: "แผนที่เสี่ยง", path: "/map" },
  { name: "ข้อมูลชุมชน", path: "/community" },
  { name: "จัดลำดับช่วยเหลือ", path: "/priority" },
  { name: "แจ้งเตือน", path: "/alert" },
  { name: "รายงาน", path: "/reports" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className="bg-gray-100 text-gray-800">
        <header className="bg-blue-700 text-white p-4 font-bold">
          <div className="container mx-auto">
            <nav className="mt-2 flex items-center justify-between">
              <span>DSS Flood Management (POC)</span>
              {/* You can add a top navigation bar here if needed */}
              <ul className="flex space-x-4">
                {menus.map((menu) => (
                  <li key={menu.path}>
                    <a
                      href={menu.path}
                      className="hover:text-blue-200 transition-colors"
                    >
                      {menu.name}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          </div>
        </header>
        <main className="p-6 max-w-6xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
